version: '3.8'

services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb
    restart: always
    ports:
     - 9091:8080
     - 28015:28015
     - 29015:29015
    command:
      - /bin/bash
      - -c
      - |
        rethinkdb create --initial-password toor
        rethinkdb --bind all
    volumes:
      - db:/data

volumes:
  db:
    driver: local
