version: '3.7'


services:
 
 mysql:
  image: mysql:${MYSQL_VERSION}
  container_name: mysql-dev
  restart: always
  ports:
    - ${MYSQL_PORT_LOCAL}:${MYSQL_PORT_DEFAULT}
  environment:
    MYSQL_ROOT_PASSWORD: ${MY_MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${MY_MYSQL_USER}
    MYSQL_PASSWORD: ${MY_MYSQL_USER_PASSWORD}
    MYSQL_DATABASE: ${MY_MYSQL_DB}
  volumes:
    - ./mysql/db:/var/lib/mysql
    - ./mysql/log:/var/lib/log
  networks:
    - databases

 postgres:
  image: postgres:${POSTGRES_VERSION}
  container_name: postgres-dev
  restart: always
  ports:
    - ${POSTGRES_PORT_LOCAL}:${POSTGRES_PORT_DEFAULT}
  environment:
    POSTGRES_ROOT_PASSWORD: ${MY_POSTGRES_ROOT_PASSWORD}
    POSTGRES_USER: ${MY_POSTGRES_USER}
    POSTGRES_PASSWORD: ${MY_POSTGRES_USER_PASSWORD}
    POSTGRES_DB: ${MY_POSTGRES_DB}
  volumes:
    - ./postgres/db:/var/lib/postgresql/data
    - ./postgres/log:/var/lib/postgresql/log
  networks:
    - databases

 firebird:
  image: kpsys/firebird
  container_name: firebird-dev
  volumes:
    - ./firebird/db:/usr/local/firebird/data
  ports:
    - ${FIREBIRD_PORT_LOCAL}:${FIREBIRD_PORT_DEFAULT}
  networks:
    - databases

 mongo:
  image: mongo:${MONGO_VERSION}
  container_name: mongo-dev
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: ${MY_MONGO_USER}
    MONGO_INITDB_ROOT_PASSWORD: ${MY_MONGO_USER_PASSWORD}
  ports:
    - ${MONGO_PORT_LOCAL}:${MONGO_PORT_DEFAULT}
  volumes:
    - ./mongo/db:/data/db
    - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
  networks:
    - databases

 redis:
  image: redis/redis-stack-server:${REDIS_VERSION}
  container_name: redis-dev
  restart: always
  ports:
    - ${REDIS_PORT_LOCAL}:${REDIS_PORT_DEFAULT}
  volumes:
    - ./redis/db:/data
  networks:
    - databases
   
 rethinkdb:
  image: rethinkdb:${RETHINKDB_VERSION}
  container_name: rethinkdb-dev
  restart: always
  ports:
    - ${RETHINKDB_PORT_LOCAL}:${RETHINKDB_PORT_DEFAULT}
    - ${RETHINKDB_PORT_CLIENT_LOCAL}:${RETHINKDB_PORT_CLIENT_DEFAULT}
    - ${RETHINKDB_PORT_INTRACLUSTER_LOCAL}:${RETHINKDB_PORT_INTRACLUSTER_DEFAULT}
  command:
    - /bin/bash
    - -c
    - |
      rethinkdb create --initial-password ${MY_RETHINKDB_USER_PASSWORD}
      rethinkdb --bind all
  volumes:
    - ./rethinkdb/db:/data
  networks:
    - databases
   
networks:
  databases:
