version: '3.7'

services:
  flowise:
    image: flowiseai/flowise
    restart: always
    environment:
      PORT: ${PORT}
      CORS_ORIGINS: ${CORS_ORIGINS}
      IFRAME_ORIGINS: ${IFRAME_ORIGINS}
      FLOWISE_USERNAME: ${FLOWISE_USERNAME}
      FLOWISE_PASSWORD: ${FLOWISE_PASSWORD}
      FLOWISE_FILE_SIZE_LIMIT: ${FLOWISE_FILE_SIZE_LIMIT}
      DEBUG: ${DEBUG}
      DATABASE_PATH: ${DATABASE_PATH}
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # DATABASE_SSL: ${DATABASE_SSL}
      # DATABASE_SSL_KEY_BASE64: ${DATABASE_SSL_KEY_BASE64}
      APIKEY_PATH: ${APIKEY_PATH}
      SECRETKEY_PATH: ${SECRETKEY_PATH}
      FLOWISE_SECRETKEY_OVERWRITE: ${FLOWISE_SECRETKEY_OVERWRITE}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_PATH: ${LOG_PATH}
      DISABLE_FLOWISE_TELEMETRY: ${DISABLE_FLOWISE_TELEMETRY}
    command: /bin/sh -c "sleep 3; flowise start"
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./.flowise:/root/.flowise
    networks:
    - default
    - db

networks:
  default:
    name: flowise-network
  db:
    name: database-network
    external: true
