version: '3.9'
services:
  ollama:
    image: ollama/ollama:0.1.13
    container_name: ollama
    volumes:
      - './data:/root/.ollama'
    ports:
      - '11434:11434'
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - default

networks:
  default:
    name: ollama-network
