version: '3.7'

services:
 nginx:
  image: nginx:${NGINX_VERSION}
  container_name: OKAN__nginx-dev
  restart: on-failure
  ports:
   - ${PORT}:80
   - ${PORT_SSL}:443
  volumes:
   - ../public_html/:/usr/share/nginx/html:rw
   - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
   - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  networks:
   - web
   - php-fpm
   - db
networks:
 web:
 php-fpm:
  name: php_php-fpm
  external: true
 db:
  name: database-network
  external: true

