version: '3.8'
services:
  redis:
    container_name: redis-stack-server
    image: redis/redis-stack-server:edge
    restart: always
    environment:
      REDIS_ARGS: '--save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81'
    ports:
      - '6379:6379'
    volumes: 
      - db:/data
volumes:
  db:
    driver: local
